# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jEiJMUQzgx23f1MZtJ-jcAq1SCp-eXWM
"""

import streamlit as st
import joblib
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder

# ── Page Configuration ──────────────────────────────────────────
st.set_page_config(
    page_title="Stroke Risk Predictor",
    page_icon="🧠",
    layout="centered"
)

# ── Load saved model and transformers ───────────────────────────
@st.cache_resource
def load_artifacts():
    """Loads the trained model, scaler, and feature selector from disk."""
    model    = joblib.load('stroke_model.pkl')
    scaler   = joblib.load('scaler.pkl')
    selector = joblib.load('selector.pkl')
    return model, scaler, selector

model, scaler, selector = load_artifacts()

# ── Helper Functions ─────────────────────────────────────────────
def get_bmi_category(bmi):
    """Converts raw BMI value into a category label."""
    if bmi < 18.5:   return 'Underweight'
    elif bmi < 25:   return 'Normal'
    elif bmi < 30:   return 'Overweight'
    else:            return 'Obese'

def get_age_group(age):
    """Converts raw age into a life stage group label."""
    if age < 18:     return 'Minor'
    elif age < 40:   return 'Young Adult'
    elif age < 60:   return 'Middle Aged'
    else:            return 'Senior'

def encode_input(raw_input_df):
    """
    Applies label encoding to categorical columns.
    Uses the same encoding logic as the training pipeline.

    Parameters:
        raw_input_df : DataFrame with one row of raw user input
    Returns:
        Encoded DataFrame ready for scaling and selection
    """
    le = LabelEncoder()
    df = raw_input_df.copy()
    cat_cols = df.select_dtypes(include='object').columns
    for col in cat_cols:
        df[col] = le.fit_transform(df[col])
    return df

def preprocess_input(user_data):
    """
    Full preprocessing pipeline: encode → scale → select features.

    Parameters:
        user_data : dict of raw values from the user
    Returns:
        Preprocessed numpy array ready for model prediction
    """
    # Build base DataFrame
    df = pd.DataFrame([user_data])

    # Add engineered features
    df['bmi_category'] = df['bmi'].apply(get_bmi_category)
    df['age_group']    = df['age'].apply(get_age_group)
    df['risk_score']   = (
        df['hypertension'] +
        df['heart_disease'] +
        (df['age'] > 50).astype(int)
    )

    # Drop id (not a feature)
    df['age'] = df['age'].astype(int)

    # Encode categorical columns
    df_encoded = encode_input(df)

    # Scale using saved scaler
    df_scaled = pd.DataFrame(
        scaler.transform(df_encoded),
        columns=df_encoded.columns
    )

    # Select features using saved selector
    df_selected = df_scaled[df_scaled.columns[selector.get_support()]]

    return df_selected.values

# ── UI Layout ────────────────────────────────────────────────────
st.title("🧠 Stroke Risk Predictor")
st.markdown("Enter patient information below to assess stroke risk.")
st.divider()

# ── Input Form ───────────────────────────────────────────────────
col1, col2 = st.columns(2)

with col1:
    gender         = st.selectbox("Gender", ["Male", "Female"])
    age            = st.slider("Age", min_value=1, max_value=82, value=45)
    hypertension   = st.selectbox("Hypertension", [0, 1], format_func=lambda x: "Yes" if x else "No")
    heart_disease  = st.selectbox("Heart Disease", [0, 1], format_func=lambda x: "Yes" if x else "No")
    ever_married   = st.selectbox("Ever Married", ["Yes", "No"])

with col2:
    work_type      = st.selectbox("Work Type", ["Private", "Self-employed", "Govt_job", "children", "Never_worked"])
    residence_type = st.selectbox("Residence Type", ["Urban", "Rural"])
    glucose        = st.slider("Avg Glucose Level", min_value=55.0, max_value=272.0, value=100.0)
    bmi            = st.slider("BMI", min_value=10.0, max_value=98.0, value=25.0)
    smoking_status = st.selectbox("Smoking Status", ["never smoked", "formerly smoked", "smokes", "Unknown"])

st.divider()

# ── Prediction Button ────────────────────────────────────────────
if st.button("🔍 Predict Stroke Risk", use_container_width=True):

    # Package raw user input into a dict matching training columns
    user_data = {
        'gender':            gender,
        'age':               age,
        'hypertension':      hypertension,
        'heart_disease':     heart_disease,
        'ever_married':      ever_married,
        'work_type':         work_type,
        'Residence_type':    residence_type,
        'avg_glucose_level': glucose,
        'bmi':               bmi,
        'smoking_status':    smoking_status
    }

    # Preprocess and predict
    processed    = preprocess_input(user_data)
    prediction   = model.predict(processed)[0]           # 0 or 1
    probability  = model.predict_proba(processed)[0][1]  # probability of stroke

    # ── Display Result ───────────────────────────────────────────
    st.subheader("Prediction Result")

    if prediction == 1:
        st.error(f"⚠️ High Stroke Risk Detected")
        st.metric("Stroke Probability", f"{probability*100:.1f}%")
        st.warning("This patient shows elevated stroke risk. Please consult a medical professional.")
    else:
        st.success(f"✅ Low Stroke Risk")
        st.metric("Stroke Probability", f"{probability*100:.1f}%")
        st.info("No immediate stroke risk detected based on the provided data.")

    # ── Risk Factor Summary ──────────────────────────────────────
    st.subheader("Patient Risk Summary")

    risk_factors = []
    if age > 50:          risk_factors.append("🔴 Age over 50")
    if hypertension == 1: risk_factors.append("🔴 Has hypertension")
    if heart_disease == 1:risk_factors.append("🔴 Has heart disease")
    if glucose > 140:     risk_factors.append("🟡 High glucose level")
    if bmi > 30:          risk_factors.append("🟡 Obese BMI")
    if smoking_status == "smokes": risk_factors.append("🟡 Current smoker")

    if risk_factors:
        for factor in risk_factors:
            st.write(factor)
    else:
        st.write("✅ No major risk factors detected.")

# ── Footer ───────────────────────────────────────────────────────
st.divider()
st.caption("Built with Streamlit · Stroke Prediction ML Project · For educational purposes only")